messageLoginSuccess = "//p[normalize-space()='You are successfully logged in.']"
overviewChart = "//h2[normalize-space()='Overview Chart']"
quickLinks = "//h2[normalize-space()='Quick Links']"
latestFive = "//h2[normalize-space()='Latest Five']"
bestSellers = "//h2[normalize-space()='Best Sellers (Aug-2024)']"
menu_Products = "//span[normalize-space()='Products']"
menu_Products_ListProducts = "//span[normalize-space()='List Products']"
menu_Purchases = "//span[normalize-space()='Purchases']"
menu_Purchases_ListPurchases = "//span[normalize-space()='List Purchases']"